{-# LANGUAGE OverloadedLists #-}
module Parts.Random (randomInit) where

import Data.Map qualified as M
import Data.Text (Text)
import Data.Text qualified as T
import Data.Vector (Vector)
import Network.IRC.Client hiding (nick)

import Utils

randomQuoteCommand :: Vector Text -> Command
randomQuoteCommand qs src@(Channel _channel _nick) args = do
  let target | n:_ <- args, T.length n < 32 = n <> ": "
             | otherwise = ""
  q <- pickRandom qs
  replyTo src (target <> q)
randomQuoteCommand _ _ _ = pure ()

randomInit :: IO Commands
randomInit = do
  let lyttonCommand = randomQuoteCommand lyttleLytton
  pure $ M.fromList
    [ ("compliment", randomQuoteCommand compliments)
    , ("lyttlelytton", lyttonCommand)
    , ("lyttle", lyttonCommand)
    , ("lytton", lyttonCommand)
    , ("lytt", lyttonCommand)
    ]

lyttleLytton :: Vector Text
lyttleLytton =
  [ "He slammed the door in my face, loud and sharp, like an acoustic lemon."
  , "When the Egyptians first discovered a method to preserve bodies (known as mummification), he knew this was what he wanted for himself when his time came."
  , "Once upon a time there was two princesses named Jenna and Martha they were twins with blue eyes each and brown locks that makes everyone falls in love with them."
  , "She was tired after her birth but this did not stop her to ask her Mother, why she was Born. \8220well, Child, a prophecy said it\8221."
  , "Unfortunately, my mother was stolen away from me by death on the day I was born."
  , "\8220Waaaah\8221 cried the infant as the very bad murderer murdered the ever loving shit out of its mother."
  , "\8220Jessica, before I let thou into Heaven, thou must solve thine own Murder,\8221 said God."
  , "As P. I. Mento gazed out at the corpses strewn atop the tub, he understood at once. They had drowned themselves\8212to death."
  , "The large and beefy Detective Scott was hunched over his desk like an overcooked shrimp, pink and coiled with a rubbery toughness I couldn\8217t wait to taste in the courtroom."
  , "Sarah had enjoyed true crime podcasts, until the day that crime became true for herself."
  , "My paramour had struck me, that harsh slap of damp skin demolishing my domestic life as the fall of an ironed curtain."
  , "The bullet pierced her heart like a Claire\8217s employee piercing a 12-year-old girl\8217s ears."
  , "The bombs fell at night, so we could only hear them until they lit up by exploding on the ground."
  , "Boom! The orphanage blew up as the blood of all the orphans flew across the street and into the river as if Jesus turned the water into wine."
  , "Brian watched the Sun explode and he screamed louder than it as his body was rapidly incinerated."
  , "She had a face like a chair, in all the best ways."
  , "My father always believed that vaccines caused autism; but what he did not tell me, I realised, as I stared into Dr. Fenton\8217s eyes, was that they also caused love."
  , "He pressed down on her like a clothes iron, as if she was an iron-on label and the duvet was a school uniform."
  , "\8220In medias res,\8221 Ms. James said aloud as she wrote it on the board. \8220Who can tell me what this means?\8221 But when she turned back to the class, they were all staring out the window at something outside."
  , "I was running at Mach cheetah through the streets, faster than me or my enemies could even fathom."
  , "\8220You\8217re not cut out for Wall Street, pal,\8221 Billy said, leaning back in his chair and cracking his knuckles like crack cocaine, before the man before him broke into big American tears."
  , "Anne was unaffected by the tall man\8217s glare. His gaze just caromed off her smiling teeth."
  , "Pete could party\8212grain alcohol to his liver was like normal grain to a thresher."
  , "His eyes were the color of the ocean, and deep also like the ocean, and also full of surprises like the ocean."
  , "The suburban mom flaunted her unseasoned chicken breast white boobs, tucked away in her Lululemon breast prison. This was the last time the world will see her creamy casserole-like flesh orbs."
  , "The blaze of the fire went snap, crackle, pop, as if imitating my favourite cereal."
  , "\8220Good morning, Herr Professor,\8221 said Inge, her hands clasped over her shirt-clad breasts."
  , "Bella was a peaceful girl; which is surprising, as \8220Bella\8221 means \8220Wars\8221 in Latin."
  , "The great sn\8217\240ar\185 Khei\8217an surveyed her ript\491s\178 from all nine ceutr\237ei\179, and sighed\8212her kuro\180\246n\8308; were faring poorly this y\254o\8309."
  , "Mother was enjoying a glass, and her son gamed on, telling teens over the mic to get schwifty."
  , "Elliot was an effeminate man, often called a term which the author is in no position to use or reclaim."
  , "If you are a right-handed person, you are my oppressor and you do not have my permission to read this book. It is not for you."
  , "I said to the dealer, \8220I am on the spectrum. I am on the spectrum, and I need to leave this boring casino.\8221"
  , "The night Gilbert left her, Lily paced around the room in circles, like a lonely car on a moonlit Hot Wheels track."
  , "He was short and fat, like his penis, which was also both, but this story is not about his penis, but about him instead."
  , "I suckled from my morning coffee like a calf from her mother\8217s bountiful teat."
  , "\8220With whom did you leave my 30 million bucks?\8221 snarled Jacko, the Uzi in his hand as polished and deadly as the grammar in his mouth."
  , "The night was black and thick, thickening every minute, as though some dark god had mixed the darkness with flour, corn starch, or some other thickening agent."
  , "My life exploded on the day I found my wife galloping, like the fifth horseman of the apocalypse, Cuckoldry, upon her fateful steed, my brother\8217s manhood."
  , "Detective Shepherd was a toothbrush of the law, scrubbing the plaque of criminality from the bloody gums of society."
  , "\8220Another murder. I hate these crimes,\8221 said Inspector Jack Slaten. He hated them even more than he hated other crimes."
  , "The occupant of the vehicle was a 5'7 Latino male, about 145 pounds, with black hair & brown eyes. I, a 5'11 Caucasian male, 200 pounds, with brown hair & blue eyes, approached on foot."
  , "Detective Horne took a pensive drag from his vape pen."
  , "I was Icarus, she was the sun, and the once-glittering poetry of our love was my wax-fastened wings."
  , "The sorrowful sun sank into the tears that were the waves, and Sammy too began to cry a bit."
  , "He wrote his name in the wet concrete. His finger the pen, his arm the pen and his body the pen holder."
  , "It was really happening. Jesse Evans was dumping that bitch Kathleen, and two lunch tables away, Hailey\8217s heart was pumping like its life depended on it."
  , "James turned the key in his new front door like he was turning away from his sins and over a new leaf."
  , "Dr. Shockter shocked her with his electricity powers just as seeing her adoption papers had."
  , "The sun rose through the diner behind which Thomas as a boy had often gone to kiss girls\8217s window."
  , "When my wife was killed, all I could think about for months was the uncalled-for uxocide."
  , "The day I died the coroner declared my death a suicide, but later we would learn the truth: that the world had murdered me."
  , "Jennifer finally became into a woman and blood dumped out her wet folds triumphantly."
  , "I\8217m wearing an off-the-shoulder gown with a gigantic hoop skirt, thought the princess as she descended the staircase."
  , "\8220I\8217m ravenous\8221 said her gurgling belly, to which she replied by eating a sandwich."
  , "She licked her own human tears from her face as she found it brought her comfort."
  , "I felt blue, and my glum mood was reflected back at me in the same colored sky."
  , "The brilliant smoke of darkstone fyre choked out the light of the brightstar."
  , "Winter\8217s hauberk jangled its victorious rhythm as she thrusted her dirk at the wyvern."
  , "As their blades clashed, Vilmor was shocked to find the hardness of his stropathian steel blade outmatched by the hardness of his opponents one of vorhoovian copper."
  , "I slammed on my brakes harder than a wall of bricks."
  , "Mike\8217s front door opened, the force of a freshly kicked door powering the sudden movement."
  , "Percy and his 10th grade theater teacher, Mrs. Loveheart, had a non-grooming love greater than Shakespeare could have ever imagined."
  , "The wrath of Achilles ( he/him | white | bisexual | demigod | ENFP | BPD ) is my theme."
  , "Oh crap the deadlines in 4 hours I\8217m just going to dictate this on my phone and hope it goes well um um so there is this guy getting into a car and his name is Steve um keep talking keep talking"
  , "From across the room, she held my eyes with the same grip with which she used to hold my hand."
  , "Her face struck me like a baseball bat, kneecapping my heart."
  , "Jason and Laura may have loved each other, but they were as sharply different as Pacific and Atlantic."
  , "The skin of her neck was bruised like a banana\8217s, and the shape of the marks betrayed that someone had left them there, unlike the banana, which bruises for unrelated reasons."
  , "\8220What do you think?\8221 I asked Boss, but her lips were as firmly crimped as the edge of an Uncrustable."
  , "Bethany and Hubert Hummel sat happily making a gingerbread house, unaware that their marriage was as brittle as Mr. Gingerbread\8217s limbs."
  , "Madeleine, the first brunette cheer captain in the history of St. Paul High School, fell like Lucifer from the roof of the Dwight L. Moody Memorial Science Building."
  , "The sun shone through the window like a high-power COB LED collimated by a reflector dish and passed through a Tyndall-effect suspension to simulate Rayleigh scattering."
  , "Night fell like a hammer dropped on the Moon, at a completely uniform speed unaffected by air resistance."
  , "Not unike how mitochondria gives energy to the cell, Alice gave energy to John\8217s heart and penis, both of whom containing dozens of cells."
  , "Sunlight touched my breasts like I do during female masturbation."
  , "Her breasts heaved with anticipation, ready to go to space. Soon they would quiver at the slightest tremor, finally free after decades in a gravity well."
  , "Mariachi song danced in my soul as my loins purred like the Prius we test drove that afternoon, scattering their bouquet inside her dynamite womanhood."
  , "I lusted for her like an asexual man who\8217d come to develop a strong attraction towards the opposite sex."
  , "My Tinder fling\8217s breasts vibrated with horniness as her lithe frame slivered out of her tiny black dress."
  , "The fan blew cold air making her nipples as hard and aroused as the audiobook of Karl Marx\8217s Communist Manifesto made my mind."
  , "So, it all started the day I stood up to Tyranny. \8220I will not put on a mask,\8221 I said heroically to the Starbucks employee like a modern Rosa Parks."
  , "John Castor stared grimly at the shimmering holographic visage of the Chairperson, smirking wokely as she commanded him to choose his method of Cancellation."
  , "The doors of my heart were as closed as those of the Capitol, that morning of January 6th."
  , "Ophelia had long dreamt of this, she mused, as she found a vampyre jaggedly masticating her crimson lifeblood."
  , "Jeffrey\8217s golden orbs gazed over the horizon, as the burning eye of the sun began to make its grudging appearance."
  , "A smile rolled up and parked itself on the scene that was his face."
  , "\8220This is why I hate your generation!\8221 seethed George after his failed proposal to the girl whose 18th birthday was now ruined."
  , "Ouch! Ouch! Why didn\8217t anyone ever tell me loving that chick would hurt so bad?"
  , "Peru. Cambodia. New Zealand. Loneliness. Alexander Tremont was an explorer, not just of the world, but of his feelings."
  , "\8220Schlormp\8221 went the knife as she plunged it into my heart, breaking it not only physically, but also emotionally, since I loved her."
  , "Boom boom pow, went my car\8217s elite sound system as I blasted the 2009 hot summer hit, \8220Boom Boom Pow\8221."
  , "Sarah didn\8217t care what her parents said. She was wise beyond her years, and so she knew that Devon only lied to and belittled her because he was afraid of hurting her."
  , "I walked up to the young painter, hand on the gun in my dress pocket. They had sent me back for him. \8220Herr Hitler,\8221 I said. Our blue eyes met and I knew: I could change him."
  , "\8220Cowabunga,\8221 whispered the time traveler\8212lest the weasel-eared security robots overhear his totally radical tendencies."
  , "\8220Prepare to die, gaijin!\8221 vociferated Lady Oni as she swung her futuristic katana at master hacker Jack Shadow, her bulbous bosoms swaying jubilantly with her gracefully spastic movements."
  , "Dale saw the murdered wife and pet; his suburban, revenge\8209less life was over."
  , "Joe killed everyone he met because he was a murderer. He even killed a policeman before (you aren\8217t supposed to kill policemen)."
  , "\8220Oh no!\8221 I cried, as a hail of bullets brutally murdered my three wonderful children."
  , "Brazil: green in the summer, blood red in the favelas."
  , "0.1 Selected Maps of the Land of Erbundia ......... clvii"
  , "Thanks to my family, without whom this book wouldn\8217t exist, and to Google Translate, without which Fran\231ois\8217s half of this book wouldn\8217t exist."
  , "The train maneuvered North by Northeast, yet Winnow D\8217Argento\8217s elven heart had long ago been totaled in a total derailment."
  , "My mind was racing, NASCAR style."
  , "Every time he smirked, David was reminded of his dad, who loved to smirk."
  , "They say it takes a village to raise a child, but even a city could not dim Lexie\8217s spirit."
  , "\8220Clang! Clang!\8221 protested the knights\8217 swords, as they were each stopped by the metal wall of the other."
  , "She tucked her bra-length hair away from her eyes."
  , "John craved Stella\8217s lips like an infant rhesus monkey craved cloth mother."
  , "My man has a voice like a lion eating dark chocolate."
  , "The sun set over the southern Italian hillside like a meatball rolling off a plate of spaghetti."
  , "She was fair and young, like a ball of fresh mozzarella cheese."
  , "I awoke to find sunlight shining through my bedroom window, like it was the middle of the night and thousands of flashlights were outside my window."
  , "Maria\8217s love pricked me, like an EpiPen pricking an enchanting diabetic woman."
  , "I slapped open the door with the haste of a black mamba."
  , "McGreer smirked at his stunned opponent on the floor. His hands that would be for helping are for hurting now."
  , "Warren softly wept over the tender brests that contained the now unbeating heart of his wife."
  , "Thog stretched luxuriously, the morning light brushing hungrily over her luscious prehistoric breasts."
  , "\8220Yum, oof, argh!\8221 My friend was having sex, as I could tell from the noises."
  , "Jennie\8217s heart was pounding, her hymen trembling, and Mike was shy to infiltrate both."
  , "I tried to fix the you-shaped lacuna in my heart with a cadre of vacuous women and vacuous pussy."
  , "When he first saw her, blood rushed into his head, and not only his head, but also his pants, and then there was this wonderful explosion, not of blood, but of the juice of life."
  , "As I walked briskly into the crowded and steamy room, I could feel the vagina inside my head dripping in anxiety."
  , "Madilyn Jenson\8217s blood type was O-positive (the tastiest for vampires), but to the dismay of Jake and his vampire friends, she guarded it like a prized possession."
  , "Richard was haunted by the ghosts of his past, and unlike Slimer or Vigo the Carpathian, these were not so easily busted."
  , "Though his half-ape, half-android DNA made him immune to dying and poison, there was one thing Number 2229 wasn\8217t immune to\8212fire."
  , "\8220KRAKOW!\8221 went the bolt of lightning as it struck my 3 bedroom 2.5 bathroom house, burning it down."
  , "\8220Dammit! The perp\8217s getting away!\8221 shouted Officer O\8217Malley as he revved his 2015 Ford Transit Connect Wagon LWB XL into gear."
  , "Little Jessica pondered how to seat her ten playmates around the table, but none of the 181,440 arrangements (ignoring rotations and reflections) seemed quite right."
  , "Try as he might\8217ve to resist (Nxg7+), Birgitte castled and captured (Kd8 Qf6+! Rde1!! Nxa2+ Qc1) her way to checkmate John\8217s king; but not his heart."
  , "The human body is over 95% water, and so too is the human family."
  , "The little mermaid went on land to kiss a prince, but everyone was wearing masks, because (and she didn\8217t know this) it was COVID times, and so her fantasy quest begins."
  , "Though his science lab had vanquished many a bacterium, Doctor Edgar knew not a vaccine for the heart of woman."
  , "In an already trying year, we were forced to take our work home\8212even the murderers."
  , "\8220I guess it\8217s just Bell Biv now,\8221 murmured Special Agent Lance Bass, squatting over the lifeless DeVoe."
  , "Hope Wolfwood\8230 If women were men, she was Superman."
  , "Shawn Hardwick stood anxiously in his room, disassembling and reassembling his gun like he learned how to in Seal Team Six training."
  , "Jennifer gawked in awe. Every last one of the three men was more handsome than the last."
  , "The farmer sprayed his crops with neonicotinoid pesticides as he filled his lungs with the paleonicotinoid nicotine."
  , "The children flowed through the class door as my mind registered them\8212brown, black, brown and golden haired Luci."
  , "The moon shone her pock-marked visage earthwards, casting her imperfect luminescence on the frolicking youth below."
  , "A father washes the dishes. His hands tighten with the tightness of someone who had lost grip of something precious years ago, maybe his wife."
  , "\8220The time is nigh!\8221 The words zoomed from synapse to synapse as Seth clutched the baton from his teammate, determination oozing from his sweat glands."
  , "Kendra knew in her heart that her struggles were first-world problems, but she tackled them with third-world tenacity."
  , "Craig vaguely stared at his ceiling while wave after wave of Post-Traumatic Stress washed over him. This is what mental illness feels like, he mused."
  , "As I sat there in the warm wetness of the pool, I felt like maybe I knew what it was like to be the shaft seated within the warm wetness of a woman\8217s tubes."
  , "\8220Go on, introduce your beloved guest into my lady garden!\8221 I whimper with my ripe talk circle."
  , "All the men were hard, all the women were wet, and at that moment, Brett was thrilled to be bisexual."
  , "Our love could start a war, she Vagrilo Princip and I Glanz Ferdinand."
  , "I was on a fast train to Boner-town the picosecond I glimpsed her gazongas."
  , "Behold Lucia! Her delicious tits were the bee\8217s knees."
  , "Stroking the enviable keyboard with all of their hands, the female hackers\8217 curvaceous outlines seemed endless: like C-like \8220for\8221 loops with no second arguments."
  , "Yessica Miller (Arch-Private, newly enlisted) stood naked in the med-scanner while its cold gaze hungrily swept her. \8220I see we have one of our more fully-figured recruits,\8221 the scanner intoned."
  , "Like most women, Rose began life as a fetus, not knowing she would bloom into a beautiful, young flower of a girl."
  , "Marilyn Kingsley, whose nationality could only be described as \8220vaguely Armenian and about one-third Mesoamerican,\8221 was unfairly rich, not only in Aztec gold but also in Caucasian beauty."
  , "Hannah was quite rich, but unlike the majority of the upper class, she was also rich in kindness."
  , "Zoseph Misawa gazed into the holo-mirror. He was a dark-haired man who looked Caucasian but wasn\8217t really because this was the future and races aren\8217t the same as they are now."
  , "\8220Your life matters!\8221 I cried in solidarity, tenderly hugging the POC."
  , "This story is so woke I\8217m going to let you, dear reader, choose whichever race/ethnicity/etc you want these characters to be."
  , "Before Brayden even realized it, the racial slur had already escaped his edgy mouth. The obnoxious child cried at everyone not to \8220hit report\8221, but there was no evading this permaban."
  , "\8220You\8217re in trouble, mi amigo,\8221 said the alcalde, which means mayor in Spanish, to the criminal."
  , "Dusk was setting in over Dresden, as Uwe looked up to see a string of star-spangled B-29 bombers rise above the sundown lit horizon. \8220Oh no,\8221 he muttered from under his breath in German."
  , "She told me \8220Watashi wa mae ni anata ni atta koto ga arimasen. Anata wa hij\333 ni hansamudesu\8221 (I haven\8217t met you before. You are very handsome.), and my face lit up like the sun that is our homeland."
  , "THE FULL TEXT OF THE CONSTITUTION OF THE FEDERATIVE REPUBLIC OF MARS (Plot starts on page 27):"
  , "One day, Eugene Evans came home from his job at AstroSpace, Inc., and sat down on his chrome living-room couch, munching on a hydrolyzed protein nutrition bar."
  , "The chess master at the park was in full combat mode, making his moves faster than even Albert Einstein ever could."
  , "Cripes! I yelled. I couldn\8217t stop saying it. Cripes! Cripes! She was dead."
  , "In 1706, in the depths of winter, Benjamin Franklin, from his mother, Abiah Folger, was extruded."
  , "Megan realised her marriage was dead the year she lost her mother to a long illness, which had ravaged the latter as Megan\8217s husband had ravaged the former, early in their marriage."
  , "I feel sad. Out of my amethyst orbs poured the new glass orbs hitting my petite lover\8217s golden, luscious, beautiful forehead as I weep."
  , "\8220Ouch!\8221 I shouted at the top of my lungs, filling the scenery with a scream that I did due to pain."
  , "She, Annabelle, gave an unreserved wail, \8220I hate stupid wishing wells and other deception items!\8221"
  , "Oogor Orkson let out a curdling hell scream and plunged his rigid warpick deep into elven flesh; this was not an Age for soft long-ears, but hard green men."
  , "Once upon a time, it was 1:30 p.m. on a Tuesday."
  , "Richard Dawkins looked on in astonishment as the wine and the bread transsubstantiated."
  , "Joan took in the scene before her as her heart took in more blood than usual."
  , "Hiya! Ugh! Keeaih! These are the sounds that are heard every day in Spike and Blade\8217s ninja training. Backflips would be heard too, but for their silence."
  , "I can\8217t help but wail as the sirens do; loud."
  , "My feet ached but my new trainers still looked sharp and so did my murder knife. Both were red."
  , "My knife penetrated her flesh again and again and again and again, blood falling to the floor like a heavy flow month without feminine hygiene products."
  , "It was a beautiful sunrise, but Brian was not happy at all. This morning was a mystery; all of his chickens have disappeared and his rooster was not alive; he did not sing this morning as he used to."
  , "Sarah felt distinctly apart from the other children at her lunch table, silent as they passed their cellphones back and forth, memeing and loling amongst themselves."
  , "They say to write what you know, so this one\8217s about my mom :)"
  , "He couldn\8217t choose a favorite child between the apple and orange of his loins."
  , "Inasmuch as I was driven insane by the horrors which follow, my descriptions of them will often devolve into mad cackling (ex. \8220hahahahaha\8221)."
  , "\8220One such as you cannot know what grief truly is to a vampyre,\8221 Viktor whispered breathlessly, \8220but perhaps if I bare my soul you will grasp some piece.\8221"
  , "This is my story, me telling it before the talented writer Stephen King\8212writer of the 1996 classic The Regulators \8212can beat me to it."
  , "Magical though her school bus may have been, no amount of that selfsame magic could save Ms. Frizzle\8217s marriage."
  , "This is the tale of a yeeted heart."
  , "As he turned his gaze toward the water, he winced\8212she used to love water."
  , "It is the things we love (like oxygen) that kill us (because it corrodes our DNA)\8212and she was the oxygen I breathe."
  , "Robot. Steel. Love. Tears. Ronnie (a robot) cried as his master ordered him to kill his love, who was also a robot."
  , "Keith scoffed as he tossed aside another tawdry, dime-a-dozen romance novel. It was clear that none of these so-called authors had ever experienced anything close to actual true love. Not like he had."
  , "Ethan, a full head and shoulders above the gaggle of bridesmaids, bisected the bright sunlight on the sharp angles of his face."
  , "Taron stared at his disgusting eggy bald head in the ovular silver disk on the wall."
  , "\8220Why learn 7th-grade English when I could be looking at Jason Usher\8217s dark, green mysterious eyes?\8221"
  , "Young, nubile Vanessa, having been raised in the church, was proud of her purity. But she took one look at James and thought, \8220I think I\8217m ready to try sex.\8221"
  , "\8220Are you okay?\8221 asks my sister Tlaloc. \8220You\8217re as green as the parrots that inhabit this part of the continent.\8221"
  , "Sally was fully prepared to slide down the water slide to impress Frank akin to how her eggs slid from her ovaries down her pubescent Fallopian tubes."
  , "As the fireman entered the burning building, he felt a warm rush blow over him\8212like when you open the oven door and get that jet of warm air."
  , "Braeden was more handsome than Philip the Handsome, the first Habsburg king of Castile, who ruled for two months before dying of typhoid fever."
  , "Humph eyed the corpse, its face split in two in much the same way as the Brexit referendum had divided her native country in 2016."
  , "\8220To be or not to be\8221 is not the question when one is born onto the lowest rungs of society; one simply has the choice \8220not to be\8221 thrust upon them like a dirty blanket."
  , "Light flowed like butter into the morning windowpane."
  , "I woke, my nipples saluting the sultry 7 a.m. sunlight slinking through the blinds to splash across my pert breasts."
  , "Her perfectly formed breasts swayed soothingly as I (also a woman, this isn\8217t a \8220male gaze\8221 thing) fell in love with them."
  , "Tiffany had always dreamed of attending the Gathering, but even as Shaggy 2 Dope and Violent J stomped triumphantly onstage, she couldn\8217t take her eyes off Brian."
  , "Truant children mocked Jack Tranton as he walked. He could have easily dispatched them with his military training. But he ignored them."
  , "The canvasser at my doorstep was attractive, but not my type. I knew as soon as I saw her that she was the kind of leftist who felt her feelings were more important than any facts on the ground."
  , "The POTUS (President of the United States), who was Bernie Sanders instead of Donald Trump, started his job for the day."
  , "My hand swam into her cinereous hair, sexily greeting the greyish strands with innumerable fingers."
  , "Natalie, an atypical girl, sat reading \8220Beowulf\8221 as her uneducated girl peers sniggered around her."
  , "The shadowy figure stood alone in the rain on the street corner under the dim yellow streetlight, casting a long thin shadow down the alley perpendicular to him."
  , "The dame\8217s hat lifted off by the wind and settled on the ground, revealing the head."
  , "With my palm perfectly flat, her horse bit me anyway\8212any trust for the equine bolted in that moment as surely as it did with the carrot I\8217d hoped to win its own with."
  , "If I\8217d have known then that it would be my own brother under the clown mask, under the phantom pirate mask, I never would\8217ve agreed to split up and check it out, not for a million Scooby Snacks."
  , "Manfred, Freya the Viking goddess\8217s last raid\8217s 9-months-later surprise, cried for nursing. Meanwhile Blutdurst, the passionate and devoted battle-axe, urged for sharpening."
  , "This is the heart-warming story of Ella and how she accepts the tElla of God\8217s love, gets rMegannge on her school bullies and achiMegans success in life!"
  , "I am Barrister. Barr Johnson Mark a lawyer in Cotonou Benin Republic. Mr.Jorge., a gold merchant, who was my client died as a result of lung cancer. Now I want to present you as the next of kin."
  , "As I felt the vampire sexily drinking the blood from my neck, the warmth between my legs grew both in wetness and in fear for my life."
  , "The girl with the vegan pork regarded me with eyes more kind than the nonviolence on her plate."
  , "Eric-san had only one goal in life: make Kimiko-chan his waifu-chan."
  , "\8220Thou must bewarest of woman, little Abu,\8221 quoth wisely the Master. \8220For while her eyes holdeth the sweetness of a hundred dates, her lips holdeth the sting of a thousand scorpions.\8221"
  , "Commander B. G. Robinson is very feminine and graciously endowed: everything she has two of are perfectly matched, coordinated, and move with a wonderful grace that is called \8220woman.\8221"
  , "Let me tell you about Sally. Her tits were good."
  , "She walked in with a dress the paralyzing green of the BlackWidow Ultimate Stealth 2014 Edition Elite Mechanical Gaming Keyboard by Razer (4.5 stars, 37 customer reviews)"
  , "I had always been the kind of woman to put my career first, but as I prepared to abandon my crying children to go to work for the hundredth time, a thought struck me\8212\8220Was this His plan for me?\8221"
  , "You find a cave (you\8217re a male Half-elf). The female Full-elves inside try to restrain their libidos, but that\8217s like butterfly nets trying to stop 100 mph of uncooked rice."
  , "Agent Gunner Storm closed his steely grey eyes and pictured the erotic sphere of Lady Liberty\8217s bare breast as he thrust into the terrorist princess."
  , "My lamestream friends told me to start dating again, but I knew the jet fuel of love couldn\8217t melt the steel beams of my heart."
  , "Texas \8220Cheap Shot\8221 Jack, the famous Newark poker player, sighed about his life. Matters of the heart\8212unlike the hearts he held in his hand\8212could not be folded so easily."
  , "A tear rolled down her face like a tractor. \8220David,\8221 she said tearfully, \8220I don\8217t want to be a farmer no more.\8221"
  , "The puddle detective Amelia Stone stepped into reminded her of a pool of blood or sins as dark as the muddy water."
  , "There is no human hunger like unto the hunger for pride."
  , "\8220It looks like this continent is out of water,\8221 I said in Antarctica, as a rookery of penguins waddled thirstily by."
  , "Dany approached the castle. (If you\8217ve forgotten about Dany, reread books 3 - 6). In her hand, she held the sword Justificier (reread book 7), still bearing the blood of Durin (reread book 9)."
  , "The brute was reminiscent of an ancient Ethiopian warrior, bristling with muscle and melanin, yet Charlie was unfazed."
  , "Unhesitantly I skydove, commending my body into the lightweight but capable hands of my parachute."
  , "Tad quit school to paint the canvas of Google Maps, his dad\8217s Camry his brush and his mind his own."
  , "THE BULLET JOURNAL OF KELSEY JOY To-Do: 1/1 - 1/7 * Three-year anniversary w/ partner in crime!!! ^ Appointment w/ ob/gyn - Study for LSAT + Solve sister\8217s murder"
  , "\8220Climate change is real,\8221 squawked the lady scientist to an auditorium crammed full of human sheep who didn\8217t question a word she said. \8220And I can \8216prove\8217 it.\8221"
  , "The millennial squirmed, but there was no entitling her way out of the firm grip of reason."
  , "Tanner was triggered once again, but a microaggression wouldn\8217t stop him this time."
  , "It was autumn, and the last leaf of liberty had fallen from the tree of tyranny onto the dirt of destruction."
  , "This is the story of how I found my Father in Heaven, but it begins with my mommy, lying back as the cruel forceps tore apart my still forming yet passionately beating human heart."
  , "Tagg could scarce believe his young eyes as they met the feast laid out richly before him: all manner of mealbreads, ripest canteloons, and\8212by the Star!\8212an entire bandersnort, carved and dripping."
  , "Dudley was a magician (not a wizard like in those Harry Potter books, and also he didn\8217t have a wand like in them), who was poor."
  , "Neera was a born disruptor, ready to take things and make them 2.0 ."
  , "Thornmill Greyeyes was a proud elf. His ears stood proud, his cock stood proud, but most of all his heart stood proud as he watched his bride mince down the isle with her ravishingly good looks."
  , "Once upon a time, there lived a beautiful princess named Annabelle. She had lovely golden locks and sensuous blue eyes\8212a sparkling Aryan jewel, just like you! :)"
  , "The mists ran like dew over her green-eyed scarlet locks."
  , "His tired blue-eyed gaze hit the lanky blonde and then turned to the brunette."
  , "The new client\8217s titties could make a grown man cry a river, and Detective Johnson was in his own personal Pacific Ocean of sexy."
  , "\8220I\8217ve got a feline these cats didn\8217t know what they unleashed when they picked a bone with me,\8221 snarled Rex Steele, chief dogtective of the Paws Angeles Petlice Department. \8220This time, it\8217s fursonal.\8221"
  , "Hashtags of the murder were all over my newsfeed."
  , "\8220Yeah,\8221 I said as he asked if my beautiful wife got murdered yesterday (she did)."
  , "Simon has been friends with Darkness for a long time, like in the song \8220The Sound of Silence\8221 by the protagonist\8217s namesake & Garfunkel."
  , "This is my coming-of-age story. Not literally, like the movie \8220Big\8221, starring Tom Hanks, or the movie \8220\&13 Going On 30\8221, starring Jennifer Garner, although those are both good movies."
  , "1 . YOU, the Anagramancer, stare down the invading MANTICORE: Will you ROMANCE IT (turn to 123), give it CREMATION (turn to 213), or summon EROTIC MAN (turn to 312)?"
  , "His steel - corded muscles pressed into her body, so close there was scarcely room to breathe beneath the pillowy swell of her breasts."
  , "The hot Florida sun battered my recently bruised shoulders that were a part of the activities where my virginity was lost."
  , "\8220The time was now and the location was here; I\8217m ready,\8221 thought nubile, 18-year-old Jenny as she lay fertilely on Johnny\8217s bed, blithely unready for the future."
  , "I first laid eyes on her at a mutual friend\8217s wedding. Her body shone through her dress; it wasn\8217t unbecoming, but you could see enough."
  , "She wanted to be loved like most women do, but was mostly ignored like the Alpini in the 12th Isonzo-Battle."
  , "\8220I\8217m breaking up with you\8221\8212her words shot into my heart, like bullets from the gun that her mouth was like."
  , "Her wit was sharp like a lawnmower blade\8212it could cut you down to size (which she could adjust, like a lawnmower)."
  , "\8220Oh no,\8221 Alex gasped when realization crashed over her like the ocean wave soon to be killing her."
  , "\8220Ah, little Abu,\8221 sighed wisely the Master as his eyes roved the desert sands. \8220When will it be that the Muslim, the Christian, and the Jew learn to listen together to the sound of the wind?\8221"
  , "Just as the equine bott fly invades its host equus to inject its larvae, Ted\8217s glowing aura now infected Mary\8217s every thought."
  , "\8220I only wish He would understand me like you do,\8221 Rebecca sighed, twirling her fingers not only through her auburn hair but also the horse\8217s."
  , "There she was, staring at the sunset, wondering why it was blue\8230 then she remembered she was staring at it through the sad filter of her tears."
  , "Almo gripped the hysteric female. \8220Tranquilize yourself!\8221"
  , "The newly single Macho Man certainly wasn\8217t ready for the pain caused when Miss Elizabeth hit him with an elbow from the emotional top ropes."
  , "The rain was pouring, but I cried harder, my tears sweeping away into the gutter where I belonged."
  , "Susan drank water, the liquid of life, unaware that soon death would be hers."
  , "The day began like any other. My alarm clock rang at 6:51 a.m. and James Brown told me that he felt good\8212he knew that he would. If only I myself had known that later, I would not feel good."
  , "\8220So the \8216establishment\8217 likes opera, huh?\8221 I thought to myself. That\8217s when I had the epiphany that started it all. \8220Well, let's see how they handle a rock opera!\8221"
  , "G 0 bl 1 n always told me: \8220You can\8217t speedrun life, Ph 4 z 0 r; not even tool - assisted.\8221"
  , "She turned to her side and watched the people nearest to her, starting the process of listening."
  , "It all started when my topaz eyes looked up into his soft emerald ones."
  , "1993, it is the future. Acid rain had destroyed civilization."
  , "The usually handsome left side of my darling husband\8217s face spasmed a full 90 degrees into horror when I told him my little secret."
  , "Some girls never get a pony, but Jane was good and her daddy loved her."
  , "This is a story about an ENFP and an INTJ who fall in love."
  , "\8220He was approximately 182.88 centimeters tall and 90.7185 kilograms,\8221 the nice guy converted to the European police officer."
  , "\8220Cucks! You\8217re all cucks!\8221 I passionately exclaimed."
  , "Torval found great pleasure in his elfin mother\8217s lips; edgy, huh?"
  , "8:32 P.M., April 17th, 1996. Detective Fry cuts open the plastic cover on his TV dinner, while not seven miles away, a similar knife slides over the neck of an innocent man."
  , "The rain thundered on the roof of the casino, washing away the grime on top, but not being able to wash away the sins within."
  , "\8220Good heavens,\8221 Jonathan murmured when he looked at the sky, for the heavens he saw were not good at all."
  , "Ebony watched over the rain-wet street, her raven hair slicked by the rain. The roof was lonely, but she preferred the honest ugliness of the gargoyles to the beautiful lies of her shallow \8220friends\8221."
  , "It was a time of darkness in the land of Gath-ka\8217noug. But then, out of the darkness, there shone a brilliant light. And the name of that light was: Horick the Elf."
  , "Call me Bastardo Medio, for my costume is black, my skin is pasty white, and I am one muy malo hombre."
  , "Amy was not going to be the only girl in her seventh-grade class without a boyfriend, and she knew just how to get one."
  , "They were ensnared, their limp limbs bound together like a bunch of Twizzlers that had melted in the sun."
  , "Blood was bursting from her arm like melted red rockets."
  , "Her curves were the Pavlovian meat that made a man\8217s loins salivate."
  , "Her eyes were like deep, green pools of eyeball liquid."
  , "All characters in this novel are purely fictitious, with the exception of Dr Alpha Wiseman, whose blog posts are my own."
  , "The reason, you ask? The reason, I say, that you\8217re going to love this book, well, it\8217s simple. You\8217re going to love this book because I\8217m a fuckin\8217 wordsmith. You\8217re welcome."
  , "Ben slams the packet down by the Officer. \8220These are my kids don\8217t you see?\8221 His own dear flesh, his dear old blood."
  , "Gunther sashayed across the street one day and heard the cry of a gun."
  , "The individual stroked his mustache, following it up with a stroke to his beard."
  , "Yeah, it kicks ass to be living in this high-rent apartment with my girlfriend who\8217s real hot and I fuck her."
  , "Agent Felicia Stone was tough and she was smart, but she still had the emotions of a woman."
  , "\8220How did you do that?\8221 gasped Danielle in astonishment as Eric ran up and down the hill with astonishing speed."
  , "The boy had a bounce in his step and a certain marsupiality of the face; we called him Kanga. But the girl, oh ho ho ho the girl, her we just called Jennifer the Bitch."
  , "I drew my customized Kimber 1911 .45, with the Pachmayr grips and skeletonized trigger, and leveled it coolly at the African-Americans."
  , "\8220The experiment of multiculturalism has failed,\8221 noted Captain Perry as he removed the laser-bayonet from the brown man\8217s chest."
  , "The bastard mayor tossed the money to his criminals. \8220Heh heh heh,\8221 everyone said."
  , "\8220Why do you love me?\8221 asked Wildflower. \8220I love you because you are brave, strong, beautiful, tough, kind, spunky, and pure,\8221 said Damien, \8220and unlike all the others, you stood up to Dictator James.\8221"
  , "The sky was gray, fitting for this grim dystopia."
  , "\8220Mom,\8221 I asked my mom. \8220What\8217s for breakfast?\8221 \8220You know I haven\8217t made breakfast since your father died in a mysterious car crash a year ago on your birthday,\8221 she said sadly. \8220You have his eyes.\8221"
  , "Though she may have wiped away the tears, they just couldn\8217t stop flowing. Like a wound on a patient without enough platelets, it kept pouring out, rapidly filling in the paths she tried to remove."
  , "The cattle-rustler\8217s whip sang through the air like a long thin snake."
  , "Do you have the time To read a little rhyme? I can rhyme for ages, For 400 pages!!!"
  , "With the brassy tocsin of his morning alarm clock, John Michaelson\8217s weary eyes exploded open."
  , "Night falls in East L.A. with the crimson blood of men, as the day rises with women\8217s tears."
  , "David fell into Greg\8217s manful arms and cried against his waiting muscles."
  , "Nothing would ever stop reminding me of Lisa and her body."
  , "So we all had dicks, all of the boys\8212can I go on?"
  , "The dancers undressed; Liam noted their respective vulvae."
  , "All the girls at the school talked about makeup and boys, but Sheila wore ripped jeans and didn\8217t care."
  , "I hope you discover, my dear teenagers, reading about my life as a \8220rebel\8221, that doing what your parents say isn\8217t always bad, cuz it can be bitchin\8217 sometimes."
  , "Ten years ago in the war, the only thing in which I thought I would be was \8220the shit,\8221 not this mansion where I live at now."
  , "I knew that Billy had hiked into my life on a trail of broken hearts, but I never guessed that mine too would soon be becoming a part of that trail."
  , "They had the mettle of men, and yet they ate the biscuits of dogs."
  , "Jorge was helplessly gripped by the sight before him, like cojones in the hand of an expert dominatriz ."
  , "\8220Together, we will beat them all,\8221 she whispered, caressing the circlet-girt fontanelles of her #royalbaby."
  , "As we gazed into each other\8217s eyes, Colin moved the front bits of my hair off my face and put them with my other hair."
  , "As the abandoned temple crumbled, Professor Winston cried, \8220Utilize your rope!\8221"
  , "All humans work at The Factory, which is run by robots and it makes more robots."
  , "It was 1995 the year the soccer teams came, kicking their balls, to town."
  , "\8220Well, this is passing strange,\8221 thought Shakespeare as he saw the dead body of the lady in Stratford-upon-Avon, \8220and methinks it dost bear investigating.\8221"
  , "\8220This sure is a bad murder,\8221 quietly thought Detective Gaius Hanssen as he was investigating a hell of a crime at the Colosseum in Ancient Rome."
  , "\8220The Crime Lads have done it again,\8221 I realized grimly, surveying my dead wife."
  , "As he stared into her fiery alabaster eyes, the wealthy Earl Roderick realized that Lady Serena was not like the other Regency-era noblewomen he had known."
  , "I gently began to fuck Tracey, and as the fucking continued we swept down and across the floor like midnight dancers."
  , "Darla lay aside her man, yowling cat noises in the glow of their grownup lovedance."
  , "Their passionate love took flight as an explosion of sprawling limbs and content genitalia."
  , "I couldn\8217t believe what I heard as I read the words in her note which, like daggers, sliced up all my feels."
  , "Phil\8217s tears fell softly, carried down his face by the gravity of her unfairness."
  , "No one could love a dark-past\8217d vampire like me."
  , "Nils awoke, contemplating the things of love."
  , "Dave, sitting there, thought to himself quietly about all the different things in the world."
  , "The man with black skin took the big rubber ball and jumped and put it into the basket with a metal rim on a board."
  , "\8220No!\8221 raged the swimmer, his opponent streaking by to touch the wall like a dolphin, \8220No.\8221"
  , "Ah, the first time I set eyes on Asia\8230 a whole new world of rich descriptions and evocative atmospheres was unveiled before my eyes."
  , "New York in the 80s: money was tight, but homies were tighter."
  , "The mean loudmouths at Orangedale High just didn\8217t understand Timmy, who only wanted to stay quiet and read and appreciate nature."
  , "Stepping into the trinket shop, the musty air inhaled by Glenda\8217s lungs went unnoticed, distracted by the air of wonder inhaled by her eyes."
  , "Dark. Cold. Vast. Shards, falling. Shapelessness. Formlessness. A wheeling, as of stars. Yes: you are inside my cerebral cortex, suckling on my thoughts."
  , "Welcome to WikiPlot, the free novel that anyone can edit! LOL JOHN LIKED POO"
  , "The rain loudly hits the sidewalk like bacon sizzles in a skillet, thinks Jake as he holds his coat collar closed, wishing he could trade the bitter cold for that meaty heat."
  , "Casie did not enjoy the preference dreams, like lemon \8211 red pepper \8211 onion; she much preferred the simple dreams, like orange \8211 orange."
  , "The men greeted each other, wearing various smiles on their faces."
  , "The stranger rode into town with eyes that said his sixgun would have stories to tell, if it spoke any language other than the guttural tongue of violence."
  , "The town was built in the lowlands, risking flood, as if the founders dared the mighty mountains surrounding the town by asking for giant rivulets of detritus, saying \8220Give me them\8221 to the mountains."
  , "My dear wife jolted awake, rolled over, and looked at me. \8220I just lucid dreamed that I killed you,\8221 she said sadly."
  , "We had succeeded in evaluating the strengths and needs of the enemy battlestation. \8220Eureka,\8221 I exclaimed. Prepare to utilize Attack Plan Theta on the rear defensive shield!"
  , "Madison was a shy, awkward, inwardly beautiful teenaged girl just like you."
  , "Pius XIII stood on the balcony, triumphant. Earlier, when the white smoke had vacated the chimney, not one citizen of FurRome would have bet on a Shibu\8208Ina to emerge."
  , "Charging, sprinting, loping with great speed, the cheetah lunged at Theodore Roosevelt, but he already had that cheetah dead to rights."
  , "\8220This isn\8217t fair!\8221, wept Case, who had previously been the team captain but due to events yet to be described was not now."
  , "\8220Please, just give me the answers to the test!\8221 said Ron. Jacob pulled his mouth over his teeth as if to say \8220I am not going to give you the answers.\8221"
  , "Jacques entered out of the rain, drenched from that selfsame precipitate."
  , "Carrie sat alone, at the most expensive restaurant in town, for the third time that month. Maybe if she turned her violet-eyed head the right way, she would get swept off her feet by a gorgeous man."
  , "The fast man raced quickly after the other man, while a third man tried to keep pace with the first man."
  , "The sex I had with a girl last night filled me with a feeling of 100% Grade A joy."
  , "John ejaculated with such strength as if to say \8220I love you Mary.\8221"
  , "Amy gasped for her last breath, as she entered the intoxicating room of her brother."
  , "\8220BOOM!\8221 said the bomb very loudly."
  , "It was a beautiful night, and the full moon glew like it had never glown before."
  , "The fireman squad extinguished the house, as it was aflame."
  , "Sirens had always made Simon feel safe, like being inside a strong man\8217s muscles."
  , "As all true prophets know, the lips of fate are tightly sealed, and only the crowbar that is the passing of time can manage to pry them open."
  , "Taft slid slowly, carefully into the bathtub. He knew that it would be the best bath that he and the bathtub had ever had."
  , "Agent Jeffrey\8217s trained eyes rolled carefully around the room, taking in the sights and sounds."
  , "Bang! As the bullet hit her ear, she felt an excruciating pain, as if her ear were screaming into itself."
  , "She had the kind of face that made you want to say hey, look at your face."
  , "\8220I\8217m a winner,\8221 thought Seabiscuit, galloping across the finish line."
  , "\8220There was to be boxing,\8221 Steve muttered. \8220Punch, punch, punch.\8221"
  , "I parted her legs with great solemnity. \8220Hello old friend,\8221 I whispered."
  , "As I approached the dairy aisle, wondering what milk to buy, I remembered my doctor suggested a low fat milk, so I purchased skim milk."
  , "Dolly looked upon her paper expeditiously then elevated up her pencil. She had now commenced not only a race against the clock, but a race to get the best mark ever in the class."
  , "Wow. He was firmly mesmerized by her bright blue eyes that complemented her blue floral dress."
  , "Her golden hair bounced in the breeze like farm-fresh honey flowing from a jar."
  , "The moon shone like a star, while tears of heaven rained the sky."
  , "A lone plastic grocery bag fluttered in the breeze, like a sail without a boat."
  , "She was really really hot, her breast like flames to my heart and mind."
  , "Today was the night where our love was to be consummated, by making love."
  , "Albert Einstein claimed that the only universal constant is light. However, Einstein never witnessed the power of Vittoria Lionheart\8217s love."
  , "\8220Do you still love me, John?\8221 I asked. \8220I don\8217t love you, Marie,\8221 came the reply from the letter I held in my shaking hands."
  , "Even as I leaned on the lamppost, the sadness of my heart could not be brightened."
  , "It was the worst possible news he could have received. He howled an inarticulate howl of rage, and threw the various decorations on his mahogany desk all across the small room."
  , "Gramlax the Mighty raised his broadsword overhead and swung it mightily, roaring, \8220You fellows will certainly pay!\8221"
  , "Kaldor fondled the hilt of his sword with his lanky fingers and inhaled the sunrise. \8220I taste the future blood of my enemies,\8221 he relished."
  , "Melissae\8217s ears, which ears were long and pointed on account of her proud elfin heritage, were perked up."
  , "Robert woke up in a hospital bed and he couldn\8217t remember the criminal man he had just killed moments before."
  , "My pen allowed me to write this tale, your eyes to read it, your mind to \8220get it\8221."
  , "Just as we were moving from the wedding to the reception, Mother demanded, \8220Show me by the way that you dance that you are.\8221"
  , "Stephen knew today felt wrong, as he listened to \8220Heart Cooks Brain\8221, by the band \8220Modest Mouse\8221, from the album \8220Lonesome Crowded West\8221."
  , "The cat sat in silence on the window sill, doing catlike things while watching his owner tend to the makings of supper."
  , "Sheila woke up instantly; it was that dream again\8212the one with the face, and the man, with the face."
  , "The red hot sun rose in the cold blue sky."
  , "\8220Pfft\8221\8212he knew the silent but deadly whisper of a silenced SIG SG 550 rifle with a 650mm barrel and a 254mm rifling twisting rate."
  , "This is the story of how one woman overcame breast cancer by never ever losing faith in herself."
  , "When my homie pulled out his gat, the first thing I said was, \8220That is very tight!\8221"
  , "Cowboy Bret said to Dave (another cowboy), \8220Now let\8217s rustle up these cattles.\8221"
  , "A wind was blowing from east to west, as if it were the sun, blowing instead of shining."
  , "I passed the fledgling plastic to the checkout chick. \8220Cred?\8221 she said."
  , "Zandor stood in the doorway, raking the onlooking crowd with the hot coals of his eyes."
  , "The blood that was dripping onto the parched floor resembled a Rorschach ink-blot test, invented in 1921 by Hermann Rorschach."
  , "He, from a physical stature, was short."
  , "\8220Caw! Caw!\8221 went the birds as the massacres happened (the birds represent sadness)."
  , "He kissed Abigail sensually, as if to say \8220I still need you\8221 with his lips."
  , "\8220Bring me the light of your love,\8221 Steve purred into my ears."
  , "\8220My heart medication!\8221 slowly remembered Dwayne, but his lateness was a stark reality."
  , "This was the story of a brave man, a freeman, who can\8217t stop touching society."
  , "\8220AAHHH\8221 she screamed in horror as her infant rocketed from inside her towards the free world."
  , "\8220Me, I like a girl with a couple extra pounds on her,\8221 said Tom, subtly negging his target."
  , "The spice filled up my taste buds, and was quite lovely."
  , "Mongoose-to-cobra, two serpentine forms, he was my rival; are we fighting in these holes, or are we really making love?"
  , "Princess Amabel brushed her silky golden hair and tried not to think about my breasts."
  , "The detective could smell the murder on the knife."
  , "\8220NOOOOOOOOOON!\8221 cried Poirot Jr., falling to his knees and rending his fledgling moustaches, \8220But when will ze killings end?!\8221"
  , "\8220You just may be the most beautiful perp I\8217ve ever laid sensors on,\8221 thought the robot lieutenant as his humanoid partner ate donuts unaware."
  , "This story is about a man and a woman, with lots of things sticking into things."
  , "He lived in a time of stories told by many."
  , "Her \8220parents\8221, her \8220boyfriends\8221\8212Angel knew she\8217d never be truly understood by anyone."
  , "Let\8217s rap about the issues of today."
  , "No matter how hard life got, Zade thought, ska would always be there."
  , "As I stood there, looking at the ground, I thought to myself, \8220Was it all worth it?\8221, but then my train of thought was interrupted by a small, yet angry, cobra."
  , "Then she died sobbing. Except platinum-level members at my website can download an awesome premium ending that has sex instead."
  , "\8220I shouldn\8217t be saying this, but I think I\8217ll love you always, baby, always,\8221 Adam cried into the email."
  , "Splashy the whale smiled secretively, flapping his flappers and swimming."
  , "The meteor formed a crater, vampires crawling out of the crater."
  , "This is a story about a racist hero who dies at the end, probably painfully since he\8217ll get shot in the face."
  , "\8220You are the greatest human in the world,\8221 the dragon told the boy who desperately wanted to be a dragon, too."
  , "This is a mystery about a murder I committed."
  , "\8220Murder is the most terrible crime of them all,\8221 the police commissioner thought to himself as he loitered purposefully near the deli counter."
  , "Once upon a time, there was a talking lamp whose lightbulb fell out and hit a person and the person got shocked and destroyed everything."
  , "Zandor stood in the doorway, raking the onlooking crowd with the hot coals of his eyes."
  , "The general, one might have said, had a sly, sneering-smile expression upon his face."
  , "There was only one man salubrious enough to assuage my hunger for love\8212senator Saxby Chambliss (R\8208GA)."
  , "\8220You are in pain; both physical and emotional,\8221 my heart informed me."
  , "When John left me he took with him my heart, my soul, my everything\8212which included my happiness, my appetite, my energy, and even my tears!!"
  , "\8220Great Caesar\8217s Ghost!\8221 Amy sputtered. \8220What glorious lovemaking!\8221"
  , "\8220OMG\8221 texted Sue-Anne to her compatriot Ellen, \8220MY OWN PARENTS R DED!\8221 It looked like the Mystery Girls had a new mystery!"
  , "\8220Approach ramming speed!\8221 commanded Commander Klamsky, as her frigate plowed through the celestial ocean at erupting speeds."
  , "Bookended with firecrackers, her birth was an auspicious occasion, festooned with all the ornaments of her birth, and solemn."
  , "As someone who has menstruated, I thought, I could tell you it\8217s no picnic."
  , "\8220Hearken,\8221 he spake, drawing thither, \8220and alight thine eyes on yon comely maiden betwixt such knaves as they.\8221"
  , "The battlefield stank thick with writhing \8220progressives\8221."
  , "Tuesday. Africa. Lion o\8217clock."
  , "The mighty frigate Indestructible rounded the Horn of Africa and lurched east\8217ard."
  , "Pika \8230 chu, thought Pikachu."
  , "Alex turned to Gertrude, in much the same way Martin Landau turned to Barbara Bain in the opening of Space: 1999 ."
  , "For many, surfing can be a pleasant and enjoyable pastime, if you like surfing, but not Peter."
  , "Zamboni doubled\8212nay, TRIPLED over in happiness-demolishing agonies."
  , "I have the ability to go through time, he suddenly remembered while at a bus stop near a tree."
  , "Deep space. The silence of the void. Shh."
  , "Deborah walked briskly down the street with pants on her legs."
  , "Jerry\8217s wife looked forward to a romantic time with him, Jerry."
  , "\8220Ooh la la!\8221 whispered Larry in French."
  , "Farmer John admired the golden corn, sprouting from the ground like buried treasure."
  , "\8220Tectonic plates fascinate me,\8221 she says, her eyes swiftly darting from my eyes to the ground, and back again."
  , "\8220I hope I win,\8221 thought Ernest, blinking laboriously; he was proud to represent his country in the Olympics, but \8220What did it all mean?\8221"
  , "The door, which had been left open a few inches, was ajar."
  , "Because they had not repented, the angel stabbed the unrepentant couple thirteen times, with its sword."
  , "Sophi broke down in tears, like a diesel car that had run out of petrol."
  , "Her face, though scalded, was as lily-white as I could ever want as we jovially kissed."
  , "Portia, distracted, brushed the fetlocks of her steed, murmuring softly."
  , "The Ramadan tree was lit, and Aladdin joyfully sat around it."
  , "Queen Elizabeth sat alone, wondering when Napoleon was gonna get there."
  , "This story is a murder mystery\8212the mystery of a murder."
  , "John Gantry surveyed the grim aftermath of battle through the aft porthole."
  , "Hussein read the agent\8217s TSA badge, gently grazed his strong hand with hers, and whispered two words that would change her love life forever."
  , "Liz Trundy burst onto the stage to the wild applause of her fellow Mary Kay comrades, unaware that the wildest applause came from Digby Jones, NFL punt receiver, who had never let himself forget her."
  , "Bob is sad. :("
  , "Under Bob\8217s fez was another."
  , "As Lucas hunkered in the shadows waiting for his name to be called he fiddled with his cuff links, praying that this time his knife thrusts would be sufficient."
  , "FUCK. I scream and pound my monitor so hard it stops functioning for four minutes, but I\8217m not using it anyway. I\8217m crying."
  , "PEWPEW\8212Lasers!\8212PEWPEWPEW!"
  , "The thing is, you can never really tell if a person is looking out from behind their own eyes, or if the eyes are being piloted by tiny mice in swivel-chairs."
  , "Sadly, Jim retracted his penis; it obviously wasn\8217t welcome here."
  , "Sleep was about to clutch my eyes, when suddenly the text rang through my head. Peering at my phone I saw, \8220WTF? LMAO!\8221 and I could not help but smile."
  , "I observed this wheelchair dude in the vestibule. He was waiting for me."
  , "With the backbreaking work of the Gold Rush came massage techniques from across the globe."
  , "It clawed its way out of Katie, bit through the cord and started clearing."
  , "\8220Crime,\8221 declared the police captain, \8220is everywhere, crime, crime!\8221"
  , "The foot delivered an unending holocaust of pain as it rocketed into Zamboni\8217s crotch."
  , "Ah, poetic Paris: with its p\226t\233s and beaujolais, tiramisu and au jus."
  , "Emperor Wu liked cake, but not exploding cake!"
  , "The ship sliced through the ocean like wood through water."
  , "I knew it was called salsa dancing, but phew!"
  , "Beatrice was aware that many had stood before her at this sacred place, with their own reasons, but with surprisingly few footprints."
  , "Either the skeleton was a sheila, or some bloke had been sleeping with two silicone balloons on his chest."
  , "Anthony\8217s eyes bulged as we all watched, with languid, infinite slowness, his skull float across the cockpit."
  , "MacGyver had grown old."
  , "Mesa Jar Jar Binks, and thisa mesa story!"
  , "Shylockina, Queen of the Jews, surveyed her realm."
  , "\8220What a horrible future we live in!\8221 said FutureMax!"
  , "The dawn blushed; not because it was embarrassed (that doesn\8217t even make sense), but because light bends funny."
  , "The air hung heavy with the perfume of the circus\8212elephants, greasepaint and hot buttered chimps."
  , "The flowers in the meadow grew slowly, as did my erection."
  , "Tingling with joy and anticipation, Paul\8217s gonads are just exactly that way."
  , "It was more than a flirtation\8212he parted her labia like Moses did the Red Sea."
  , "For hobos, spring was the season of love."
  , "\8220BRRRRRRRRRRRIIIIIIIIING!!!!!!!!!!!!!!\8221 rang the alarm clock, awakening me from my Gamma Hydroxy Butyrate-induced slumber."
  , "BUDDABUDABDABUDDA, went the bullets."
  , "Oh no! There they were coming! Francis shut his eyes and jumped into the fray. WANG! went the shovel wielded by him against the zombies. WANG! WANG!"
  , "Scaling Everest was, by far, the most amazing and transformative experience of my life. Unfortunately, this is a thesis on context-free grammars."
  , "Eve stood there, half-eaten apple in one hand, desire burning in her eyes. Adam screamed \8220Jesus woman what the fuck have you done?!!\8221"
  , "I just recently came off a trip to the Far East, and it struck me that I was in a region of the world where wars had started."
  , "This is the cipher key for all that follows: \9614 \9615 \9615 \9614 \9615 \9615 \9615 \9614 \9615 !"
  , "Dora liked to explore."
  , "Does the dance of love have to be a dairy of romantic sonnets; can it not be a Haiku and still be sensually poetic?"
  , "\8220The hero has cancer,\8221 thought the doctor grimly."
  , "Bill\8217s goiter had burst and it was on my head, Mary thought quietly."
  , "\8220I can\8217t!\8221 screamed Jake to whomever was outside the airplane\8217s single lavatory."
  , "Cries of \8220Ahoy!\8221 broke the turgid silence of the golf course; the Cap\8217n approached."
  , "James took Mary\8217s hand\8212not in matrimony just yet, but plain physically\8212and led her to the altar."
  , "I woke up shuddering; my soul was now dead inside."
  , "Everyone in the year 2020 knows about nanobots!"
  , "The evil Intergalactic Emperor surveyed the destruction he wrought. \8220Booyah!\8221 he cried with glee. \8220I\8217m in ur base! I\8217m killing all ur mans!\8221"
  , "\8220And that\8217s when I stabbed her in the face,\8221 Jake finished. The rest of the support group looked on in horror and abject confusion. They weren\8217t sure what this had to do with testicular cancer, but they knew it had to be bad."
  , "On November the 22nd, 1963, an innocent man by the name of Lee Harvey Oswald stood inside the Texas School Book Depository, burdened with the knowledge of what would soon happen, but with no way that he could possibly prevent it. Seconds later an American presidency was destroyed. He never had a chance to tell his story. This is his story."
  , "Dear Mister Spray: I am writing to you to inform you of your son\8217s death. What follows were his last words."
  , "The door dilated 1 . 1 This is in the future, when doors dilate instead of opening the way they do now."
  , "John, surfing, said to his mother, surfing beside him, \8220How do you like surfing?\8221"
  , "Man oh man, you\8217re gonna like this book; boy howdy."
  , "Before I drop this narrative shit, here\8217s a quick shout-out to that old Classics professor who said I couldn\8217t write for jack: yo, suck me!"
  , "Get ready to take a virtual tour of sydney australia through the backyards of a kangaroo who will punch you in the head fifty times!"
  , "Braille haiku on the gravestone served to excite some while sighted visitors needed only touch the smoothly polished shapes."
  , "Dr. Metzger turned to greet his new patient, blithely unaware he would soon become a member of a secret brotherhood as old as urology itself."
  , "\8220Joy is contagious,\8221 he said, peering into the microscope."
  , "Her ovine familiar baaahed angrily."
  , "The spaceship was crashing, but, more importantly, John and Greta were having sex in it."
  , "This is the story of your mom\8217s life."
  , "\8220Tasty waffle?\8221 Jim suggested alluringly, prodding me with the afore-mentioned breakfast food."
  , "The dame had balls, you had to give her that, and a Jetta."
  , "I wanted to name the heroine Siobhan but didn\8217t know how to pronounce it\8212screwy Celtic pronunciation\8212and now I do but it\8217s too late."
  , "Juicy, their love was like forbidden fruit: tasty."
  , "We write the year 2347, a world abound with nuclear alacrity, when suddenly Frank enters with a smile."
  , "I know who the murderer is, Kevin blogged."
  , "My English teacher, Mrs. Robinson, always said to start in the middle of something interesting, so here's Peter encased in 50 cubic feet of Jell\8208O."
  , "While a hellish yowl tore my throat, the panicked kitten\8212in fact me\8212leapt crying for the throat of Julia, there seeking comfort\8212and revenge."
  , "While my opponents fellate the Satan of special interests, I go down on Reform\8217s compassionate angel."
  , "My fellow Americans, as you know, my foreign policy can be summed up in five words: \8220Iludium\8208\&236 Explosive Space Modulator\8217."
  , "Critics are calling me a fat cat, viciously ignoring the fact that I\8217ve been working out."
  , "Now, you\8217re all aware of my vocal campaign against the global slave trade, so what I am about to confess may raise a few eyebrows."
  , "I am pleased to announce that, although attitudes have improved immensely, the beatings will continue."
  , "For centuries, man had watched the clouds; now, they were watching him."
  , "It was just like Jack the Ripper, only, this time, Jack was a she, and possibly some form of time-traveller."
  , "It was the best of times, it was the worst of times; I know that\8217s a contradiction but bear with me."
  , "Sing, O Muse, of Tiffany\8217s wrath on Triple Coupon Day."
  , "It happened exactly like this\8230 well, maybe not exactly, but I\8217m fairly confident about the major points\8212not that I was there, though."
  , "Michael had always wanted to lactate."
  , "I really hope you like this book, because I wrote the whole thing totally naked!"
  , "Indubitably, this was not the sort of soup that engendered wholesome thoughts of energetic eating."
  , "The inner workings of the kidney, which you will no doubt find quite interesting, can, albeit shocking to some, be downright astonishing to others."
  , "In retrospect, Grace realized she probably shouldn\8217t have fucked a Republican."
  , "\8220Son, defenestration is your only option.\8221"
  , "Thirty days left, forty nine thousand nine hundred eighty seven words to go."
  , "The pain wouldn\8217t stop, and Vern still had three cats left."
  , "\8220I raped your sister,\8221 cruelly he sneered, \8220and now she is no problem,\8221 and my friends that is the day my heart tore a sunder."
  , "His dark heart pulsated with raw evil, as he pumped it, furiously."
  , "Listen: once upon a time (well, actually twice but I think the first one doesn\8217t really count\8230 or is that \8220didn\8217t\8221) there was some guy!"
  , "Gordon strove to be a nice pimp."
  , "Herein lurk delegitimized power structures and epistemological straitjackets and stuff."
  , "\8220Lawd a\8217mighty,\8221 howled Caleb, to the consternation of those few who still remained in the helpless, drifting lifeboat, \8220some of y\8217all are lookin\8217 mighty tasty!\8221"
  , "And that was it, more or less, except for dear Gwendolyn who had a little trouble with syphilis for some time afterwards."
  , "But Gran was once again lost in quiet reminiscence, or perhaps her epilepsy."
  , "Bound, blindfolded, and buttered, at last Leopold knew the semblance of peace."
  , "While defeating Mutantis, Gyroman lost everything, but learned that sometimes the clothes do make the man."
  , "Her sad death thirty-nine years (and four books, if my plans hold) later, would help lessen my rather unspeakable distress at this happily-ever-after ending."
  , "Maria\8217s flossing was now complete."
  , "Turning, I mentally digested all of what you, the reader, are about to find out heartbreakingly."
  , "The cosmonauts were transfixed with wonderment as the sun set\8212over the Earth\8212there lucklessly, untethered Comrade Todd on fire."
  , "Mary (who dies at the end, so don\8217t get all surprised like the stupid person who wrote me on my other book) loved Joe, a lot."
  , "If you\8217re going to start reading my novel, please stop touching yourself like that."
  , "Monica had exploded, and I had a mystery, and pieces of her pancreas, on my hands."
  , "The moon was full, the hot-dog-eating contest was over, and I had a lot of throwing up to do."
  , "A lone testicle lay in a barren field."
  , "\8220Handful of Meat\8221 was, unfortunately, more than just the name of Carl\8217s band."
  , "Jeremy didn\8217t remember eating corn or, for that matter, wearing his good loafers."
  , "Leon fell out of the goat."
  , "First, let me give you some background on the whole monkey thing."
  , "\8220Man, you won\8217t believe what happened to me tonight,\8221 Dave declared, bursting into our dorm room, \8220but first I gotta go beat off!\8221"
  , "The night passed like a kidney stone: painfully and with the help of major sedatives."
  , "Before I got hit by that ole bus, I never used to think much, but now I think PLENTY."
  , "Done with slaughtering nuns and the infirmed out of cyber-lust, Mandroid turned his optical probes towards a more pastoral (and spiritually recondite) existence."
  , "In anticipation, John licked his own lips."
  , "Hank, Herculean therapist, cleansed the Augean stables of my soul."
  , "To stand tall, to humbly crawl; to laugh, to cry; to puke bitterly, to suck on come what may\8212here follows my turbulent infancy."
  , "In 3010, the potatoes triumphed."
  ]

compliments :: Vector Text
compliments =
  [ "Ah! how the play of light upon your shoulders does bring one to reminisce of fallen lighthorsemen and gaseous trenches."
  , "A kitten's growl would not come near the plights of your spoken voice."
  , "A Latvian in pain could not attain your Gibraltar-mending squeals."
  , "Anathema comes ever to mind when thinking of you."
  , "As the bile slowly rises in my incandescent eluxulator, your mere presence has a calming effect upon my rabies."
  , "A suburban distance lying across your chest, a purpled frock befitting the asphyxiated, cans of lima beans upon your knees, you are truly a goddess of disturbed tranquility!"
  , "Beauty is cataplexed in contemplation of your multidimensional effervescence."
  , "Be still, my love, my watermelon rind. I am consumed with your collection of agile fans and pocked blades."
  , "Bleed me! My memory is fried with your pork!"
  , "BUY WAR BONDS"
  , "Ceci n'est pas un compliment."
  , "Certainly your trout are more proseperous to vaccuum than the flying coachmen of Czar Nicholai!"
  , "Cher ami, votre tendre chapeau a heurte trois de mes phalanges avec une grace incomparable."
  , "Come, let me gnaw your fingernails that I may absorb and lose myself in the wise and gritty detritus that is you."
  , "Convexion sees between your eyes. Herds of gazelle concave at your feet!"
  , "Cretins and vermin cannot compare with the depths of your cousins."
  , "Cry for the stiffness of the earlobe. The turtles are fallen and the rain stands still. How long must I suffer with your undergarments?"
  , "Demonize your sofa. It will lend forth more peanuts between the cushions."
  , "Din nese overger kun din haltende underleppe!"
  , "Dustmites the world over love you for your feet."
  , "EAT SPASMOTIC RICE! It beguiles and will improve your complexion."
  , "ENGINEER YOUR AUNT! Do it! You will be grateful for having done so. Yolutsky promises to cease diddling with your ears."
  , "Entranced by the bitter harmony of your lips, I gaze beyond reason to find the oasis of your ruptured soul."
  , "Ermine derision scalds your protuberant nares."
  , "Es demasiado tarde, pero te ves guapisimo."
  , "Ever do I seek the elusive flexures of your large intestine."
  , "Ever do you remind me of a staircase falling exotically into a sea of spilled macaroni."
  , "Ever do your tears shed forth an peal of epidermal thunder!"
  , "Ever would one thank the very ground upon which you walk that your blossoming feet be never engaged."
  , "Eyes like scars dimple your ears."
  , "Fast blinking reveals the true visage of time pieces hidden within your eyes."
  , "Fear not the earl lest I had conquered him and peopled else this isle with Calibans."
  , "Fighting for the liberty of the fruit tree tastes nothing like the glint of sagittarius rounding itself around your uvula. I know the time will soon arrive when we will see people manufactured in crates and seives of glass."
  , "Flies dance operas to your wisdom."
  , "Garbage bins would be seventh with ivy to hold your face under a stone."
  , "Give me your hand that I may want of your broken nails."
  , "Heizenmizstenwerner ut mal die westernmoviefurter und glipzenglagenheimer zieden un der witzelwaltzerfloggen..."
  , "Hermaphrodites around the galaxy desire that you turn your rock and crochet bowl to its loudest setting."
  , "His majesty's caravan is as compelling as your temper."
  , "How beautiful is the snowshine in your eyes, so directly current from the static in your brain."
  , "How can I help but use your eyes as a means for self-asphyxiation?"
  , "How lovely is your curdled priest!"
  , "I do sense a complete and utter vaccuum in the space between your auricles."
  , "I find your eye sockets to be a wondrous amusement park of neo-plastic pleasures and oncogenic delights."
  , "If I were to combine your blood, toes, and hair, it might not be you, but it would be enough for my basic desires."
  , "If seen on a disintegrating smokestack, your eyelashes would certainly compell even a wayward band of masticating cod into a feverish frenzy."
  , "If you behave there will be cake for the miscreants we call your brothers."
  , "If you were a camel your humps would be esoterically bald from overuse."
  , "Il mio cuore batte per te come un trattore al minimo"
  , "I love your eyes, but only with ketchup."
  , "I must demand your pleasing chin! How it passes there and back again like a leopard searching for its misplaced frontal lobes."
  , "In caressing your follicles I am only vaguely reminded of the bitter harvest."
  , "In hunger you most certainly drool pendulums of sinusoids and wounded mosques."
  , "In your absence I find other forms of amusement."
  , "In your presence even a batallion of body builders could pass the New York State driving exam."
  , "In your presence even my shadow acquires the sensation of touch."
  , "I relentlessly desire your custard tongue between my eyelids."
  , "I see your loves in cloves."
  , "I should welcome flagellation by your ovoviviparous torso."
  , "I surmise that your basement is made of skin and is never depleted of nurses."
  , "Its a far far better thing I do than to require that you find me a hammer and pummel me with all due diligence."
  , "I would beg to see your arms raised in calcification towards the expanding horizon as the minutemen stand before me with their phallic gums aimed and loaded.."
  , "I would gladly eat chamberpots of your sickled beans and thalassemic rice."
  , "I would sing by an aria of pain to your endearments and wiles."
  , "Kanseller din ekstreme hundekjeks innen det virtuelle livmorsf&auml;lget eksellerer."
  , "La pluie de vos insultes n'atteint pas le parapluie de mon indifference."
  , "La sola visione dei tuoi magnifici occhi mi fanno diventare ottimista per tutto cio' che riguarda la mia vita."
  , "Legions of Communists worship your robust cannabalism of Capitalists clad in junk mail suits."
  , "Les caresses de tes yeux fertiles sont plus douces que toutes les gifles de tes mains rouilies."
  , "'Lo, EUREKA,' I yelled into the cat, 'Thou art truly laborious and divergent. My nose bleeds for your impending encounter with the front fender of a Mercedes Benz.'"
  , "Luminescence breeds in your finest moments of desperation."
  , "Madame, your implement is admonishing me!"
  , "Madam! How your enormous foreskin shades me from the sun!"
  , "Madam, what a handsome moustashe you wear!"
  , "Mano a mano, le tue ossiflexe, si starnubbano nel brondio."
  , "Many sausages have known things before you had time to react."
  , "Marmots will stick to you in Delaware."
  , "May bathtubs overflow upon your offspring."
  , "May clinging breasts always come to your aid in the kitchen."
  , "May you always be as vivid as your hallucinations."
  , "May you always have stables of horses to service your needs."
  , "May you ever have naked women to toss tiny pickels an coo in oblivious delight at your witty urbane opener of foreign post."
  , "May your shit always sport dog on the bottom of your shoe."
  , "May your succulent earlobes ever flap about my knees like a thousand wooden pigeons fleeing the local sawmill."
  , "Mon amour, tu es aussi bestiale qu'une branche de cedre!"
  , "Most certainly, your fingernails stimulate magnetism in the most organic of solvents!"
  , "My elbow sockets sharpen pencils when you pass by on divine fumes of industrial combustion."
  , "My eyelids belch with effluvial afterthoughts when you tease me with gelatin and congealed chicken rinds."
  , "My pathological scar desires to cite poetry through the ruddied girth of your soul!"
  , "Never align yourself too much with the Listerine salesman."
  , "Never pet your dog when it is on fire."
  , "Never was a man so badly meant to wear corrective glasses."
  , "No results found"
  , "Oh!, how you inflict me with wounds of paranoia and desire."
  , "Optical delusions still themselves when you pass by in convexing pomp and sacral trance"
  , "Panoramic aromavision is too narrow for olfaction in your general presence."
  , "Rearing in quaffed monk, you stun me by employing eight windows when the priest is but iodine."
  , "Ringworm sleeps comfortably around your umbilicus."
  , "Sausage casings are not the intended consequence of fashionable dress."
  , "Send me your hang nails. With great eagerness I will knit them into divine papal integuments."
  , "Seven donkeys and a concubine cannot compare with the tarnished sheen left in your path of combustion."
  , "Sir, what exquisite breasts you have!"
  , "Sir, you have most exquisite breasts."
  , "Sir, you've broken your water.... may I get you a new glass?"
  , "So charmingly heathen, your skin is like a teardrop on a popsickle."
  , "Softly seething, surreal breathing.. Ignite the cannon with sphagnum lanthum.. Laud the armies of diphthongs with your superannuating Diphtheria.. And I will ever be your combustive tablature of igneous geometries."
  , "Soft sausages would gladly procreate in the bathwater of your verisimilitude."
  , "Solitamente, quando emani profumi, mi ricordi lamette circonflesse."
  , "So precisely, your head fits into the smallest of diameters."
  , "Sortons les routes des mamelles d'antan launch la joie des voleurs la nacelle se remplit."
  , "Sound barricades itself into rolls of peautbutter when you speak."
  , "Such meals that you cook! Certainly your kitchen is overrun with pestilence and vermin!"
  , "Suffer, for you are toasting the Marzipan!.. (..and may I upon pretense ring latent tintinabulations for your Andalusian raisins!)"
  , "Tabulate your monger. You will be well-flayed for the effort!"
  , "Teacups smash, flounders ignite spontaneously in your presence."
  , "Tensile congratulations on your conceptual development of obliterative existence!"
  , "The dimples of your breasts do pucker evocatively when you smile."
  , "The expanse of your intelligence is a void no universe could ever fill."
  , "The expansion (and resultant rapid cooling) of your consecrated culotte sings the golden turnip with the mulatto touch-typist in my pants."
  , "The French Foreign Legion could not match the lucid beauty of your toenails!"
  , "The glow of your teeth exudes the courage of raw liver."
  , "The goats you buy shed a perfume that makes Marxism so terribly clear to me."
  , "The Green Paint on the Walls Clouds my Thoughts of Flying Planks of Wood, Much An ocean-going tin of crosseyed mussels could never match the melodious burblings of your sister's husband."
  , "The holes in your earloabs ever make me think fondly of the pock-marked landscapes upon the lunar surface."
  , "The limpidity of your objections ever motivates my hunger."
  , "The ocean's foam matches the froth of hair streaming through your lips."
  , "The perils of your eyelashes torture my libido into a state of crass belief in Roman Catholicism."
  , "The phase of your hallucinations reminds me of those balmy days when the championship mould was breeding, when the fish were long, and so were the valued floats of men we drank through narrow straws..."
  , "The quietness of a manhole cover cannot compare with the wild vapours of nylon I sense in your larynx."
  , "The seared runes crossing your divided consciousness do speak of contemptuous cardinals setting a spanish villa ablaze."
  , "The shape of your ears is the totality of bedpans in a fit of cholera."
  , "The sisters of St. Cathode ask that you cover yourself with filaments and take pains to make yourself fully incandescent this evening."
  , "The spark of intelligence in your blinking eyes is not unlike the glow from the teeth of an electrocuted axe-murderess."
  , "The tiny sounds of ancient bees resound forth from the forrested coercions between your toes."
  , "Thine integral refractions upon a lump of coal exhibit multiple pulmonary geysers."
  , "Thine right eye so plitherates that thine left eye doth graze uopn it."
  , "Timepieces could not know your age."
  , "Transistors bridge where your vanity would never go."
  , "Tribes of primitve hunters, with rhinestone codpieces rampant, should build pyra mids of Chevy engines covered in butterscotch syrup to exalt the diastolic, inef fable, scintillated and cacophonous salamander of truth which slimes and distracts from each and every orifice of your holy refrigerator, Sears be its brand."
  , "Troglodyte kidneys measure sardonic spasms not unlike the movements of an albatross buried in creosote."
  , "Tus ojos me piden agarrarte por el cuello y exprimirlo."
  , "Uw oren zijn als vliegende schotels."
  , "Votre regard est plus penetrant qu'une stalagmite sertie dans son antre d'albatre"
  , "Wallets of fur would bombard a triassic keychain rather than dialyse in your equable fishtank."
  , "Wear stents akimbo!"
  , "Wend you not to wreak annihilable havoc with my tumefascent transmitters and turgid devices."
  , "Were giraffe's antennae to sprout from your barnacled elbows, one could but weep for the pretense of a fallen chamber pot."
  , "What beautiful negligence you wear!"
  , "Wheals and boils come forth as testament to your fine sense of haut couture."
  , "When faced with scathing winds and torrents pouring forth stain, your mind thinks cleverly to the leprous angels found in all train crashes."
  , "Where it not for the dizzy whiptail ambivalence of your crumbling fleece, I could never contemplate the ways of so many merchant bankers in heat."
  , "Woe is me, for I must forever more huddle, unminded, in the dark shadow of thine undeserved engine of procreation."
  , "Woods nymphs sprinkle your path with bowlings balls while you dance and prowl in the sequined moonlight with leftover heads of lettuce."
  , "You are a banana moon subverting the sun."
  , "You are as dazzling as a pregnant cow attired in electrical sockets."
  , "You are as effective as a linear geometry based upon the Maginot Line."
  , "You are as frightful as an engine developed solely for the countenance of sexual inuendo by country music."
  , "You are as orange as a congeleen afro curled around the bony edges of a silver spoon expressing its innermost desires for a lime-based detergent."
  , "You are as truthful as a Communist in the streets of Milan."
  , "You are more beautiful than a bouquet of fossils."
  , "You are the Ayatollah of Confusion on the night of Dival&iacute;."
  , "You are the sound of one lip kissing."
  , "You are the swordfish that will never shower."
  , "You are truly a wristwatch in a world of lumps."
  , "You blink thrice warned that I can but think of the eyebrows of Richard Nixon covering a hostess of furry twinkies."
  , "You breath as delicately as vapors of methane flowing towards an attractive flame."
  , "You cannot compare with the apex of a ferris wheel, nor the nadir of a ditch filled with a coelocanth's droppings."
  , "You do but seize my motor fixtures into a likeness not unlike the moon."
  , "You do dine so emergently that sanguine trepidation overcomes the house-staff."
  , "You enter while seven exits."
  , "You ever remind me of the enigma of postage not sent."
  , "You foment graciously, as ever any dying monster did rot."
  , "You hail the calves as eloquently as any facade of Easter Island."
  , "You have been blessed with the egregious qualities of a duffle-bag in His Majesty's Royal Navy."
  , "You have no socially redeeming value."
  , "You have not yet reached the height of your depravity."
  , "You have the intrepid appeal of a carnivorous apple on its way to a pile of cadaveric stones."
  , "You have the patience of a trilobite."
  , "You have the vocabulary of an aspidistra in panic."
  , "You look like a million paces tonight."
  , "You look like someone who has lunched poorly and who has no expectations for dinner."
  , "You meander through love as a river delta contemplating levitation."
  , "You move with the eloquence of disintegrating fuselage."
  , "You mutter such objects of equine delight that the mind's ability to sew slices of mordant ivory becomes tamed with visions of Tamils in Constantinople."
  , "Your affluent effluent drives even the most zeal-minded to imbibe."
  , "Your aquiline senescence implores me to generalize within the relms of a starfish's lifelong hallucinations of gelatin pools and of actuaries floating upon the Rhine."
  , "Your arms lengthen daily like the edges of a festering table."
  , "Your beautiful bulgarian bricks stack like the thousand eyes of Estonian potatos, peering amid fuzzy dreams of corrugated cardboard."
  , "Your brilliant hematoma does beguile the natives."
  , "Your brother's chicken coop is as abundunt as the home port of the U.S. Navy's Sixth Fleet."
  , "Your cleverness ferments meat without the need of oxygen."
  , "Your dainty nostrils flare with the humblest grandiosity of an ant swallowing a water buffalo."
  , "Your dandruff falls like the fixtures within a scenic railway passing through a thousand bearded rainbows..."
  , "Your dashingly colored toupee twists my right boot into a state of ennui with the speed and dexterity of many lemon meringue-coated conquistadors."
  , "Your ear-splitting sequels have a mind of their own."
  , "You reflections bear a turgidity that rends naked glass."
  , "Your elbow patches rumble with a fear reminiscent of mayonnaise cradled in scotchguard."
  , "Your entrance is ever a segue to endless lands of derision."
  , "Your eyebrows are as verdantly forrested as the woodworms of my most sombre dreams."
  , "Your eyelids refract the turgid limnations of an eel trapped in flickering cinematographic paralysis."
  , "Your eyes are like spheres of glue filled with shimmering worms."
  , "Your eyes are much like milky pools of pantyhose."
  , "Your eyes flash upon my cathode ray flesh in a manner that propels my viscera into an eternal state of turgid flux."
  , "Your eyes glow like naked livers burning in the sun."
  , "Your eyes shine with the greed of a misplaced tea strainer."
  , "Your eyes show as many deep and full shades of blue as a healing bruise upon an injured forelimb."
  , "Your face does bend even the most anorexic mirror into a sensuous playground of muscular spasms."
  , "Your face is like an imperfectly shaven tennis ball."
  , "Your fingers are as divine as the pope's nostril hair."
  , "Your fingers staple pine nuts into everything you touch."
  , "Your fingers sublimate into volcanic gases with the slightest cooling touch from the antennae of a passing lyre."
  , "Your hair is reminiscent of a self-digesting yak in heat."
  , "Your hair sends forth a sheen remniscent of a wounded man streaming bandage gauze from the highest church steeple."
  , "Your Hands do the work of 10,000 highly trained lesbian jumping beans."
  , "Your higher cerebrations are most post-mortem."
  , "Your higher coritcal centers ever send forth ignorant bliss and immortal contaigon."
  , "Your ideas are as fresh and new as an agatized stromatolite."
  , "Your intelligence attains the grand summation of molecular motion at absolute zero."
  , "Your intelligence is equal to the smoothness of a walnut shell."
  , "Your layers of absinthe and torsion form concretions of hyperalimentation."
  , "Your legs are like threads of cotton, though much thicker, and filled with weevils."
  , "Your love is like 1000 caucasian carnivores playing mumblety peg with an eggplant."
  , "Your mobile calluses massage even the most scarred of surfaces."
  , "Your moist towelette speaks to me in lather as the disgruntled post man listens attentively in Yidish, pumping only an iron to the mini-van."
  , "Your mother once had eyes that shone like the legs of Mae West."
  , "Your mucuous membranes glisten with the glow of reactions in the act of regurgitation."
  , "Your nasal hair speaks volumes concerning the Isle of Wright."
  , "Your nasal linings will last as long as the skin of rocks, thrust enigmatically upon a distant shorline of mating beetles."
  , "Your nose hair is pleasingly twisted with the roots of a bristlecone pine that is so precariously perched on the side of a cliff it may easily uproot and fall upon the Republican lobbyists below."
  , "Your nose hairs scare me."
  , "Your pendulous thorax makes cellists envious of the rotund sounds emanating from your nose in D minor."
  , "Your petulance is seduction unto extinction."
  , "Your pharyngeal hair tickles the divine underbelly of my terrestrial erector set with saponifying liquors."
  , "Your presence puts me in a truly albino mood."
  , "Your presence reminds one of a blind jackal, eternally dependent upon misguided archbishops to provide instruction in bowling."
  , "Your raw sensuality flusters me as the dog sneezes into the ventilation fan."
  , "Your skin emanates such a porcelain sheen that I am tempted to stamp WC under your bosom and across your armpits."
  , "Your skin sheds forth so that I endlessly crave pans of fried baclava."
  , "Your soul contains all that is found in insects, pigs and vermin."
  , "Your successful diet could mean countless pounds shed for the planet."
  , "Your sunburnt skin is as beautiful as gangrenous flesh peeled from an amputated limb."
  , "Your sweet voice is like the snap of a bra strap upon a sun burnt back."
  , "Your tears evoke a taste as memorable as honey."
  , "Your teeth are as soft as liquid stones poured from an aquamarine vase of solidifying flesh."
  , "Your timeless negligence has a way of arousing my palliative inuendo."
  , "Your unexpected explosion entangles us in a web of premature umbrellas and precocious timepieces."
  , "Your wit, your teeth, your pasty reflection can but incorporate freely into the powerful surface of a disintegrating mirror set afloat upon a swarm of locusts."
  , "Your woes provide the mechanism for cylidrical reasoning."
  , "You salivate strongly, like a platoon of army engineers trapped in a fit of malaria."
  , "You so truly know your inner plankton, it is a revelation not unlike discovering an impacted toll booth upon the plains of Patagonia."
  , "You turn the atmosphere wild with currents of vitriol when you smile at the passing insects."
  , "You wear your breasts like a man with an uncontrollable bulge in his apartment."
  , "You wear your ears well, true to the testament of loose fitting flesh."
  ]
